version: '3.7'
services:
  web:
    container_name: 'pinglingle'
    image: 'pinglingle'
    build:
      context: .
      dockerfile: pinglingle-pi.dockerfile
    environment:
      ConnectionString: Host=pingdb;Username=postgres;Password=18d9jg48;Port=5432;Database=pinglingle
    ports:
      - "8080:80"
    depends_on:
      - "postgres"
    restart: unless-stopped
    networks:
      - pinglingle-network

  postgres:
    container_name: 'pingdb'
    image: postgres
    environment:
      POSTGRES_PASSWORD: 18d9jg48
      POSTGRES_DB: pinglingle
    networks:
      - pinglingle-network
    restart: unless-stopped
    volumes:
      - pingdb_data:/var/lib/postgresql/data

networks:
  pinglingle-network:
    driver: bridge

volumes:
  pingdb_data:
